diff --git a/Makefile b/Makefile
index 4c4417c..51ca91c 100644
--- a/Makefile
+++ b/Makefile
@@ -21,19 +21,11 @@ ifeq ($(PKG_CONFIG),)
 $(error "Install pkg-config to make it work")
 endif
 
-CC ?= gcc
-CXX ?= g++
-
-COMMON_FLAGS += -O2 -c \
-	-D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 \
-	-fPIE \
-	-Wformat -Wformat-security -Wno-format-nonliteral \
-	-Wall -Wextra -Werror \
-	-Ikafel/include
+COMMON_FLAGS += -c -D_GNU_SOURCE -Ikafel/include
 
 CXXFLAGS += $(USER_DEFINES) $(COMMON_FLAGS) $(shell pkg-config --cflags protobuf) \
-	-std=c++14 -fno-exceptions -Wno-unused -Wno-unused-parameter
-LDFLAGS += -pie -Wl,-z,noexecstack -lpthread $(shell pkg-config --libs protobuf)
+	-std=c++14 -fno-exceptions
+LDFLAGS += -lpthread $(shell pkg-config --libs protobuf)
 
 BIN = nsjail
 LIBS = kafel/libkafel.a
@@ -77,7 +69,7 @@ endif
 
 kafel/include/kafel.h: kafel_init
 kafel/libkafel.a: kafel_init
-	CFLAGS=-fPIE $(MAKE) -C kafel
+	CFLAGS=-fPIE LDFLAGS= $(MAKE) -C kafel
 
 # Sequence of proto deps, which doesn't fit automatic make rules
 config.o: $(SRCS_PB_O) $(SRCS_PB_H)
